name: Go Tests

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.22
          check-latest: true

      - name: Go Tidy
        run: go mod tidy && git diff --exit-code

      - name: Go Mod Verify
        run: go mod verify

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -v -count=1 -race -shuffle=on ./...
